# Generated by Django 6.0.8 on 2026-10-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_product_barcode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'ordering': ['created_at', 'batch_number'], 'verbose_name_plural': 'Batches'},
        ),
        migrations.AddField(
            model_name='batch',
            name='expected_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Packages on the supplier document. Not the counted stock.'),
        ),
        migrations.AddField(
            model_name='product',
            name='packing_note',
            field=models.CharField(blank=True, help_text='How the package is packed, e.g. 8 pcs/bag, 10 bags/hookbox.', max_length=255),
        ),
        migrations.AlterField(
            model_name='batch',
            name='quantity',
            field=models.PositiveIntegerField(default=0, help_text='Do not use this as the live balance. Inventory is the stock figure.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('pcs', 'Pieces'), ('pkg', 'Package'), ('box', 'Box'), ('pack', 'Pack'), ('carton', 'Carton'), ('kg', 'Kilogram'), ('liter', 'Liter'), ('bag', 'Bag')], default='pkg', max_length=20),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
