# Generated by Django 6.0.8 on 2026-10-06 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_batch_options_batch_expected_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='scan_code',
            field=models.CharField(blank=True, help_text='Numeric arrival code on the parent label, e.g. 29006102601.', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='numeric_code',
            field=models.CharField(blank=True, help_text='Digits printed on labels, e.g. 290, 240, 301, 302.', max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='batch_number',
            field=models.CharField(help_text='Readable lot, e.g. LS-PAD-290-061026-01.', max_length=100),
        ),
        migrations.CreateModel(
            name='PackageUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(help_text='Package number, e.g. 1 for 0001.')),
                ('code', models.CharField(help_text='Barcode value, e.g. 290061026010001.', max_length=30, unique=True)),
                ('status', models.CharField(choices=[('IN_STOCK', 'In stock'), ('SHIPPED', 'Shipped')], default='IN_STOCK', max_length=20)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='inventory.batch')),
            ],
            options={
                'ordering': ['sequence'],
                'unique_together': {('batch', 'sequence')},
            },
        ),
    ]
