# Generated by Django 6.0.8 on 2026-10-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='Account number the customer enters on Co-op paybill.', max_length=30, null=True, unique=True),
        ),
    ]
