# Generated by Django 6.0.8 on 2026-09-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed'), ('PAID', 'Paid'), ('READY_TO_PACK', 'Ready to Pack'), ('PICKING', 'Picking'), ('PACKED', 'Packed'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
    ]
