# Generated by Django 6.0.8 on 2026-10-04 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_salesorder_status'),
        ('sales', '0002_customer_account_manager'),
    ]

    operations = [
    ]
